DATASET:
  data_path: "./data/experiment_5/prop_0_0"
  train_path: "./data/experiment_5/prop_0_0/train_80" 
  val_path: "./data/experiment_5/prop_0_0/val_10"  
  test_path: "./data/experiment_5/prop_0_0/test_10"
  num_class: 4
  img_size: 299

MODEL:
  name: "xception"
  ckpt_path: "./ckpt/experiment_5/"
  model_path:  "./models/experiment_5/xception_prop_0_0_v2"
  plots_path: "./plots/experiment_5/"

TRAIN:
  batch_size: 32
  num_epoch: 200
  augment: True
  optimizer: "Adam"
  lr: 0.001
  lr_tune: 0.0001
  es: 20
