DATASET:
  data_path: "./data/4_classes_new/prop_0_0/" 
  train_path: "./data/4_classes_new/prop_0_0/train_70" 
  val_path: "./data/4_classes_new/prop_0_0/val_15"  
  test_path: "./data/4_classes_new/prop_0_0/test_15"
  num_class: 4  # 0:1-4, 1:5-7, 2:8-9, 3:10-13
  img_size: 299

MODEL:
  name: "inceptionV3"
  model_path: "./models/4_classes_new/prop_0_0/inceptionV3_prop_0_0"
  plots_path: "./plots/4_classes_new/prop_0_0/"

TRAIN:
  batch_size: 32
  num_epoch: 500
  augment: True
  tune: False 
  optimizer: "Adam"
  lr: 0.001
