DATASET:
  data_path: "./data/4_classes_new/"
  train_path: "./data/4_classes_new/prop_0_0/train_70" 
  val_path: "./data/4_classes_new/prop_0_0/val_15"  
  test_path: "./data/4_classes_new/prop_0_0/test_15"
  num_class: 4
  img_size: 299

MODEL:
  name: "xception_tune"
  model_path: "./models/4_classes_new/xception_prop_0_0_tuned"
  plots_path: "./plots/4_classes_new/"
  tune_path: "./models/4_classes_new/xception_prop_0_0"

TRAIN:
  batch_size: 32
  num_epoch: 500
  augment: True
  tune: True 
  optimizer: "Adam"
  lr: 0.0001
