DATASET:
  data_path: "./data/propagated_2_2/"  # "./data/original/"
  train_path: "./data/propagated_2_2/train_70" # "./data/original/train_70"
  val_path: "./data/propagated_2_2/val_15"  # "./data/original/val_15"
  test_path: "./data/propagated_2_2/test_15"  # "./data/original/test_15"
  num_class: 4  # 0:1-4, 1:5-7, 2:8-9, 3:10-13
  img_size: 299

MODEL:
  name: "inception_resnetV2"
  model_path: "./models/inception_resentV2_221206"

TRAIN:
  batch_size: 32
  num_epoch: 500
  augment: True
  tune: False 
  #freeze_size: 0
  lr: 0.001
