DATASET:
  train_path: "./data/train_70"
  val_path: "./data/val_15"
  test_path: "./data/test_15"
  num_class: 4  # 0:1-4, 1:5-7, 2:8-9, 3:10-13
  img_size: 224

MODEL:
  name: "resnet50"
  model_path: "./models/resnet50"

TRAIN:
  batch_size: 16
  num_epoch: 200

