DATASET:
  data_path: "./data/4_classes/"
  train_path: "./data/4_classes/propagated_0_0/train_70" 
  val_path: "./data/4_classes/propagated_0_0/val_15"  
  test_path: "./data/4_classes/propagated_0_0/test_15"
  num_class: 4
  img_size: 299

MODEL:
  name: "xception"
  model_path: "./models/4_classes/propagated_0_0/xception_best"
  plots_path: "./plots/4_classes/"

TRAIN:
  batch_size: 32
  num_epoch: 500
  augment: True
  tune: False 
  optimizer: "Adam"
  lr: 0.001
